version: "3"

volumes:
  openstreetmap-data-europe:
  openstreetmap-rendered-tiles-europe:

services:

  ots_import:
    image: "s3pweb/ots:1.3.10"
    command: import
    environment:
      - "UPDATES=enabled"
      #- "DOWNLOAD_PBF=https://download.geofabrik.de/europe-latest.osm.pbf"
      #"- "DOWNLOAD_POLY=https://download.geofabrik.de/europe/luxembourg.poly"
      - "OSM2PGSQL_EXTRA_ARGS=-C 40960"
    volumes:      
      - /opt/osm/maps/europe-latest.osm.pbf:/data.osm.pbf
      - /opt/osm/maps/europe.poly:/data.poly
      - openstreetmap-rendered-tiles-europe:/var/lib/mod_tile
      - openstreetmap-data-europe:/var/lib/postgresql/12/main
    deploy:
      replicas: 0
      restart_policy:
        condition: none

  ots_pg:
    image: "s3pweb/ots:1.3.10"
    command: pg
    environment:
      - "OSM2PGSQL_EXTRA_ARGS=-C 4096"      
    volumes:
      - openstreetmap-data-europe:/var/lib/postgresql/12/main
    deploy:
      replicas: 0
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  ots_apache:
    image: "s3pweb/ots:1.3.10"
    command: apache
    environment:
      - "ALLOW_CORS=1"
      - "THREADS=30"
    volumes:
      - openstreetmap-rendered-tiles-europe:/var/lib/mod_tile
    links:
      - ots_pg
    ports:
      - "4080:80"
    deploy:
      replicas: 0
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  
